// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_de_Análisis_de_Ventas_ETL.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }
}